# Generated by Django 2.1.7 on 2019-03-05 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('site_code', models.SlugField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'FROZEN'), (2, 'ARCHIVED')], default=0)),
                ('publish_datetime', models.DateTimeField(blank=True, null=True)),
                ('base_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangosnapshotpublisher.ContentRelease')),
            ],
        ),
    ]
