# Generated by Django 2.1.7 on 2019-03-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangosnapshotpublisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.SlugField(max_length=100, unique=True)),
                ('document_json', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contentrelease',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='releasedocument',
            name='content_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangosnapshotpublisher.ContentRelease'),
        ),
    ]
