# Generated by Django 2.1.7 on 2019-03-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosnapshotpublisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrelease',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentrelease',
            name='use_current_live_as_base_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='releasedocument',
            name='document_key',
            field=models.SlugField(max_length=100),
        ),
    ]
