# Generated by Django 2.1.7 on 2019-03-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosnapshotpublisher', '0002_auto_20190306_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedocument',
            name='content_type',
            field=models.SlugField(default='content', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='releasedocument',
            unique_together={('document_key', 'content_release')},
        ),
    ]
