# Generated by Django 2.1.7 on 2019-03-28 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djangosnapshotpublisher', '0003_contentreleaseextraparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrelease',
            name='release_documents',
            field=models.ManyToManyField(blank=True, related_name='content_releases', to='djangosnapshotpublisher.ReleaseDocument'),
        ),
        migrations.AlterField(
            model_name='contentrelease',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='contentreleaseextraparameter',
            name='key',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='releasedocument',
            name='document_key',
            field=models.SlugField(max_length=250),
        ),
    ]
