# Generated by Django 2.1.7 on 2019-04-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosnapshotpublisher', '0004_auto_20190328_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedocument',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
