# Generated by Django 2.1.8 on 2019-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosnapshotpublisher', '0006_auto_20190408_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrelease',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
