# Generated by Django 2.1.8 on 2019-04-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosnapshotpublisher', '0007_auto_20190410_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrelease',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
