# Generated by Django 3.1.1 on 2020-10-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosnapshotpublisher', '0008_auto_20190416_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrelease',
            name='is_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contentrelease',
            name='status',
            field=models.IntegerField(choices=[(0, 'PREVIEW'), (1, 'STAGED'), (2, 'LIVE'), (3, 'ARCHIVED')], default=0),
        ),
    ]
